services:

  db_encrypt:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web_encrypt:
    build: ./app
    restart: always
    env_file:
      - ./.env
    environment:
      # Construct DATABASE_URL using the environment variables and correct hostname
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_encrypt:5432/${POSTGRES_DB}
    ports:
      - "5000:5000"
    depends_on:
      - db_encrypt


volumes:
  postgres_data:
